kind = "app"
categories = ["Graphics", "Photography"]
icon = "assets/app-icon/hicolor/256x256/apps/ai.storyteller.lightcraft.png"

[linux.x86_64]
asset = "lightcraft-{version}-linux-x86_64.tar.gz"
exec = "lightcraft-{version}-linux-x86_64/bin/lightcraft"

[linux.aarch64]
asset = "lightcraft-{version}-linux-aarch64.tar.gz"
exec = "lightcraft-{version}-linux-aarch64/bin/lightcraft"
