[package]
name = "dac-color"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Color (L0)"

[lints]
workspace = true

[dependencies]
dac-brand = { workspace = true }
serde = { workspace = true }
dac-geom = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
