//! `cargo xtask shortcuts`: regenerates `docs/manual/keyboard-shortcuts.md` from the running
//! command registry. It builds `dac-cli`, runs `app-cli snapshot --demo` with one `ui.menu.list`
//! request (every menu command with the shortcut the default Classic keymap gives it) and writes a
//! Markdown table per top-level menu. Labels that carry the product name (`{app}`) become `<app>`,
//! so the generated file passes `cargo xtask brand check`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

const OUT: &str = "docs/manual/keyboard-shortcuts.md";

fn target_dir(root: &Path) -> PathBuf {
    std::env::var_os("CARGO_TARGET_DIR").map(PathBuf::from).map_or_else(|| root.join("target"), |d| if d.is_absolute() { d } else { root.join(d) })
}

/// A menu entry as `ui.menu.list` reports it.
#[derive(Debug, PartialEq)]
pub struct Entry {
    pub menu: Vec<String>,
    pub label: String,
    pub id: String,
    pub shortcut: String,
}

/// The entries with a shortcut out of a `ui.menu.list` reply line.
pub fn parse(reply: &str) -> Result<Vec<Entry>, String> {
    let v: serde_json::Value = serde_json::from_str(reply).map_err(|e| format!("ui.menu.list reply: {e}"))?;
    let list = v.get("result").and_then(|r| r.as_array()).ok_or("ui.menu.list: no result array")?;
    let s = |e: &serde_json::Value, k: &str| e.get(k).and_then(|x| x.as_str()).unwrap_or_default().to_string();
    Ok(list
        .iter()
        .filter(|e| e.get("shortcut").and_then(|x| x.as_str()).is_some_and(|x| !x.is_empty()))
        .map(|e| Entry {
            menu: e
                .get("menu")
                .and_then(|m| m.as_array())
                .map(|m| m.iter().filter_map(|x| x.as_str().map(str::to_string)).collect())
                .unwrap_or_default(),
            label: s(e, "label").replace("{app}", "<app>"),
            id: s(e, "id"),
            shortcut: s(e, "shortcut"),
        })
        .collect())
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('`', "ˋ")
}

/// The Markdown page.
pub fn render(entries: &[Entry]) -> String {
    let mut by_menu: BTreeMap<String, Vec<&Entry>> = BTreeMap::new();
    for e in entries {
        by_menu.entry(e.menu.first().cloned().unwrap_or_else(|| "Other".into())).or_default().push(e);
    }
    let mut out = String::from(
        "# Keyboard shortcuts\n\n\
         <!-- Generated by `cargo xtask shortcuts` from the command registry (`ui.menu.list`). Do not edit by hand. -->\n\n\
         The default (Classic) keymap. `Cmd` is ⌘ on macOS and `Ctrl` on Linux, Windows and the web; `Alt` is ⌥.\n\
         Change any binding in Help → Keyboard Shortcuts (or `app.setShortcut`); Settings switches to the\n\
         Alternative keymap set. Keys that work without a menu item (ratings `0`–`5`, labels `6`–`9`,\n\
         `[`/`]` rating steps, `Shift` + key to advance) are listed in [library-shortcuts.md](../library-shortcuts.md).\n",
    );
    for (menu, list) in &by_menu {
        out.push_str(&format!("\n## {menu}\n\n| Shortcut | Command | Menu | Id |\n|---|---|---|---|\n"));
        for e in list {
            let path = e.menu.iter().skip(1).cloned().collect::<Vec<_>>().join(" → ");
            out.push_str(&format!("| `{}` | {} | {} | `{}` |\n", cell(&e.shortcut), cell(&e.label), cell(&path), e.id));
        }
    }
    out
}

pub fn run(root: &Path) -> Result<(), String> {
    let mut c = crate::cargo();
    c.args(["build", "-p", "dac-cli"]);
    crate::run(c, "cargo build -p dac-cli")?;
    let dir = target_dir(root);
    let cli = dir.join(format!("debug/app-cli{}", std::env::consts::EXE_SUFFIX));
    let work = dir.join("xtask-shortcuts");
    std::fs::create_dir_all(&work).map_err(|e| format!("{}: {e}", work.display()))?;
    let script = work.join("menu.jsonl");
    std::fs::write(&script, "{\"method\":\"ui.menu.list\",\"params\":{}}\n").map_err(|e| e.to_string())?;
    let out = std::process::Command::new(&cli)
        .args(["snapshot", "--demo", "--size", "800x600", "--script"])
        .arg(&script)
        .arg("-o")
        .arg(work.join("shot.png"))
        .output()
        .map_err(|e| format!("{}: {e}", cli.display()))?;
    let stdout = String::from_utf8_lossy(&out.stdout);
    let line = stdout
        .lines()
        .find(|l| l.contains("\"result\""))
        .ok_or_else(|| format!("no ui.menu.list reply from {}: {}", cli.display(), String::from_utf8_lossy(&out.stderr)))?;
    let entries = parse(line)?;
    let dest = root.join(OUT);
    std::fs::write(&dest, render(&entries)).map_err(|e| format!("{}: {e}", dest.display()))?;
    println!("wrote {OUT} ({} shortcuts)", entries.len());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_menus_and_hides_the_name() {
        let reply = r#"{"id":1,"ok":true,"result":[
            {"id":"a.b","label":"Quit {app}","menu":["File"],"shortcut":"Cmd+Q"},
            {"id":"c.d","label":"None","menu":["File"],"shortcut":null},
            {"id":"e.f","label":"Pipe","menu":["View","Sub"],"shortcut":"|"}]}"#;
        let e = parse(reply).unwrap();
        assert_eq!(e.len(), 2);
        let md = render(&e);
        assert!(md.contains("| `Cmd+Q` | Quit <app> |  | `a.b` |"));
        assert!(md.contains("## View") && md.contains("| Sub |") && md.contains("`\\|`"));
        assert!(!md.contains("{app}"));
    }

    #[test]
    fn bad_reply_is_an_error() {
        assert!(parse("not json").is_err());
        assert!(parse("{}").is_err());
    }
}
